Lab_Test(30-07-2021)/Models/Attendance.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab_Test_30_07_2021_.Models
{
    public class Attendance
    {
        public int AttId { get; set; }

        public int? EmpID { get; set; }

        public DateTime? CheckTime { get; set; }

        public bool? IsCheckIn { get; set; }

        public bool? IsCheckOut { get; set; }

        public string ImageURL { get; set; }

        public string Latitude { get; set; }

        public string Longitude { get; set; }

        public string Note { get; set; }

        public int number { get; set; }
    }
}

Lab_Test(30-07-2021)/Models/EmployeeInformation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SalesSolution.Web.Models
{
    public class EmployeeInformation
    {

        public int EmpId { get; set; }

        public string ID { get; set; }

        public string Name { get; set; }

        public int? Age { get; set; }

        public string Designation { get; set; }

        public int? EntryBy { get; set; }

        public DateTime? EntryDate { get; set; }

        public int? UpdateBy { get; set; }

        public DateTime? UpdateDate { get; set; }

    }
}

Lab_Test(30-07-2021)/Models/LoginInfoDAO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SalesSolution.Web.Models
{
    public class LoginInfoDAO
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserType { get; set; }
        public string EmpMasterCode { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string UserStatus { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
    }
}

Lab_Test(30-07-2021)/Models/ResultInfo.cs
namespace SalesSolution.Web.Models
{
    public class ResultInfo
    {

        public bool isSuccess { get; set; }
        public bool isError { get; set; }
        public string ErrorMessage { get; set; }
   
        public int Id { get; set; }

    }
}

Lab_Test(30-07-2021)/Controllers/AttendanceController.cs
using Lab_Test_30_07_2021_.DataLayer;
using Lab_Test_30_07_2021_.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab_Test_30_07_2021_.Controllers
{
    public class AttendanceController : Controller
    {
        // GET: Attendance

        private readonly AttendanceDal informationDal;


       public AttendanceController()
        {
            this.informationDal = new AttendanceDal();
        }


        public ActionResult AttendanceEntry()
        {
            return View();
        }

        public ActionResult Save_Attendance(Attendance attendance)
        {
            if (Session["UserId"] != null)
            {
                 return Json(informationDal.Save_AttendanceInformation(attendance, Convert.ToInt32(Session["UserId"].ToString())), JsonRequestBehavior.AllowGet);           
            }
            else
            {
                return RedirectToAction("SignIn", "UserLogin");
            }
        }
    }
}

Lab_Test(30-07-2021)/Controllers/EmployeeGeneralController.cs
using Newtonsoft.Json;
using SalesSolution.Web.DataLayer;
using SalesSolution.Web.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SalesSolution.Web.Controllers
{
    public class EmployeeGeneralController : Controller
    {
        private readonly EmployeeInformationDaL _informationDaL;

        public EmployeeGeneralController()
        {
            this._informationDaL = new EmployeeInformationDaL();
        }

        // GET: EmployeeGeneral
        public ActionResult EmployeeRecords()
        {
            
            if (Session["UserId"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("SignIn", "UserLogin");
            }
        }


        public ActionResult EmployeeSetup(int id = 0)
        {
            
            if (Session["UserId"] != null)
            {
                ViewBag.Id = id;
                return View();
            }
            else
            {
                return RedirectToAction("SignIn", "UserLogin");
            }

        }

        public ActionResult Save_EmployeeInformation(EmployeeInformation employee)
        {
       
            if (Session["UserId"] != null)
            {
                return Json(_informationDaL.SaveEmployeeInformation(employee, Session["UserId"].ToString()), JsonRequestBehavior.AllowGet);
            }
            else
            {
                return RedirectToAction("SignIn", "UserLogin");
            }
        }

        public ActionResult GetDesignation()
        {
            DataTable dt = _informationDaL.GetDesignationForDDL();
            string JSONresult;
            JSONresult = JsonConvert.SerializeObject(dt);
            return Json(JSONresult, JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetEmployeeInformationList()
        {
            DataTable dt = _informationDaL.GetEmployeeInformationList();
            string JSONresult;
            JSONresult = JsonConvert.SerializeObject(dt);
            return Json(JSONresult, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetEmployeeInfoDataForEdit(int id)
        {
            return Json(_informationDaL.GetNoticeMasterForEdit(id), JsonRequestBehavior.AllowGet);
        }

       
        public ActionResult DailyShiftSetup()
        {
            return View();
        }
    }
}

Lab_Test(30-07-2021)/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab_Test_30_07_2021_.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lab_Test(30-07-2021)/Controllers/UserLoginController.cs
using SalesSolution.Web.DataLayer;
using SalesSolution.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SalesSolution.Web.Controllers
{
    public class UserLoginController : Controller
    {
      


        public ActionResult SignIn()
        {
            return View();
        }


        public ActionResult Registration()
        {
            return View();
        }


        public ActionResult LogOut()
        {
           Session["UserId"] ="";
           Session["UserName"] = "";
            Session["LoginName"] = "";
            Session["Email"] = "";
            Response.Redirect("SignIn");
            return View();
        }


        public JsonResult GetLoginInfo(LoginInfoDAO model)
        {


            LoginInfoDAL aLoginInfoDAL = new LoginInfoDAL();

            List<LoginInfoDAO> lst = aLoginInfoDAL.LoginInfoUSerPassDAL(model.LoginName, model.Password);

            string result = "fail";
            if (lst.Count() > 0)
            {

            
                result = "Success";

            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

Lab_Test(30-07-2021)/Views/Attendance/AttendanceEntry.cshtml
@{
    ViewBag.Title = "AttendanceEntry";
}

<div class="container-fluid" style="width: 100% !important;">

    <div class="page-body m-t-20">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="card main-card  pb-4">
                    <div class="card-header main-card-head">
                        <h5 class=""> <i class="fas fa-1x fa-th-large "></i> Employee Attendence </h5>

                    </div>

                    <div class="card-body">



                        <div class="form-card">

                            <div class="row">

                                <div class="col-md-4">
                                    <div id="my_camera"></div>
                                </div>

                                <div class="col-md-4">
                                    <div id="results"></div>
                                    <p id="imgeBase64Str" style="display:none"> </p>
                                </div>
                                <div class="col-md-4">

                                    <div class="form-group row">

                                        <div class="col-sm-7">

                                            <input type="text" class="form-control" id="txtEmpId" placeholder="Employee Id">

                                            <span id="v-txtEmpId" class="invalid-tooltip fade hide" data-delay="2000"></span>
                                        </div>
                                        <span class="text-sm-left text-c-red">*</span>
                                    </div>


                                    <div class="form-group row">


                                        <div class="col-sm-6">
                                            <div class="form-check form-check-inline">
                                                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="IsCheckIn"> Check In
                                            </div>

                                        </div>


                                    </div>


                                    <div class="form-group row">


                                        <div class="col-sm-6">
                                            <div class="form-check form-check-inline">
                                                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="IsCheckOut"> Check Out
                                            </div>

                                        </div>


                                    </div>



                                    <div class="form-group row">

                                        <div class="col-sm-7">

                                            <input type="text" class="form-control" id="txtNote" placeholder="Note">

                                        </div>

                                    </div>



                                </div>

                                <br />
                                <br />


                            </div>
                            <br />

                            <div class="row">

                                <div class="col-md-4">
                                    <form>
                                        <input type="button" id="takeshot" value="Take Snapshot" class="btn btn-info" onClick="take_snapshot()">
                                    </form>
                                </div>


                            </div>
                            <hr />
                            <div class="row mt-3">
                                <div class="col-12 text-center">
                                    @*<button class="btn btn-success" style="width: 205px !important; margin: 0 auto !important;" onclick="SaveLeaveApplication()">Submit Information </button>*@
                                    <button type="button" id="btnSave" class="btn btn-sm btn-primary mb-2" style="background-color: #00bcd4;color: #fff;" onclick="Save()">
                                        <i class="fas fa-check-square"></i>&nbsp; Save Information
                                    </button>

                                </div>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>


</div>













@section Scripts{



    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/webcamjs/1.0.26/webcam.js"></script>
   
    <script language="JavaScript">
        Webcam.set({
            width: 320,
            height: 240,
            image_format: 'jpeg',
            jpeg_quality: 90
        });
        Webcam.attach('#my_camera');
    </script>



    <script language="JavaScript">


        var file = "";


        window.onload = function () {

            setInterval(function () { take_snapshot() }, 5000);
        }

        function take_snapshot() {

            // take snapshot and get image data
            Webcam.snap(function (data_uri) {
                // display results in page
                document.getElementById('results').innerHTML =

                    '<img id="base64image" src="' + data_uri + '"/>';
            });

 

            file = document.getElementById("base64image").src;
        
         

        }


        function ValidationTooltip(id, message) {

            $(id).empty();

            if ($(id).empty()) {
                $(id).append(message);
            }
            $(id).toast('show');
            $(id).css("display", "block");

        }

        function RemoveValidationTooltip(id) {
            $(id).css("display", "none");
        }
        function Validation() {

            $('#txtEmpId').removeClass('is-invalid');

            RemoveValidationTooltip("#v-txtEmpId");

            isValid = true;

            if ($('#txtEmpId').val() == "") {

                $('#txtEmpId').addClass("is-invalid");
                ValidationTooltip("#v-txtEmpId", "Please fill out of this field!");
                isValid = false;
            }

            return isValid;
        }


         function Save() {

             if (Validation()) {
    $.confirm({
    icon: 'fas fa-question-circle',
    title: 'Are You Sure ?',
    content: 'You are about to save the data!',
    theme: 'Supervan',
    type: 'green',
    buttons: {
    Confirm: {
    text: 'Confirm',
    action: function () {
    FinalSave();
    }
    },
    Cancel: function () {
    }
    }
    });

    }

    }
    function FinalSave() {


        debugger;
     
    var jsonData = {};

        jsonData["AttId"] = $('#masterId').val();
        var EmppiD = $('#txtEmpId').val();
   
        jsonData["number"] = EmppiD;
        jsonData["IsCheckIn"] = $('#IsCheckIn').is(':checked');
        jsonData["IsCheckOut"] = $('#IsCheckOut').is(':checked');
        jsonData["Note"] = $('#txtNote').val();
        jsonData["ImageURL"] = file;
    

    var urlpath = '@Url.Action("Save_Attendance", "Attendance")';
    $.ajax({
    data: jsonData,
    url: urlpath,
    type: "POST",
    beforeSend: function () {
    _open_LoadingPopUp_WithMsg("popDiv", "Please wait. Data is Saving...");
    },
    success: function (result) {
    _close_LoadingPopUp_WithMsg();
    if (result.isSuccess == true) {
    $.confirm({
    icon: 'fas fa-check-circle',
    title: 'Success !',
    content: 'operation successfully done',
    type: 'green',
    buttons: {
    OK: {
    text: 'OK',
    action: function () {
    var url = '@Url.Action("PatientInformationView", "PatientInformation")';
    window.location.href = url;
    }
    }
    }
    });

    } else {
    _saveError();
    }

    },
    error: function (data) {
    _close_LoadingPopUp_WithMsg();
    _saveError();
    },

    });
    }


    </script>

   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1 /jquery.min.js"></script>

    }

Lab_Test(30-07-2021)/Views/EmployeeGeneral/EmployeeRecords.cshtml
@{

    Layout = "~/Views/Shared/_Layout.cshtml";

     ViewBag.Title = "EmployeeRecords";

}

<style>

    #custom_table, th, td {
        border: 0.1em solid #CFCFCF;
        border-collapse: collapse;
    }

        #custom_table td {
            padding: 0.1em 6px !important;
        }

        #custom_table th {
            padding: 4px;
            background-color: #3C8BCA;
            color: white;
        }

        #custom_table tr:nth-child(even) {
            background-color: #eee;
        }

        #custom_table tr:nth-child(odd) {
            background-color: #fff;
        }
</style>

<div class="container-fluid" style="width: 100% !important;">

    <div class="page-body m-t-20">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="card main-card  pb-4">
                    <div class="card-header main-card-head">
                        <h5 class=""> <i class="fas fa-1x fa-th-large "></i> Employee Information List </h5>
                    </div>

                    <br />
                    <div class="row">
                        <div class="col-md-5"></div>
     
                        <div class="col-md-2">
                            <button id="btnShowModal" type="button"
                                    class="btn btn-sm btn-info">
                                <i data-feather="plus" style="width: 16px !important; height: 16px !important;"></i>&nbsp;New Entry
                            </button>
                        </div>
                    </div>

                    <br />

                    <div class="card-body " id="custom_table">
                        <div class="table-responsive" id="MainGradeDiv">
                            <table id="dtTble" style="width:100% !important; text-align:center;">
                                <thead>
                                    <tr>
                                        <th class="text-center">#SL</th>
                                        <th class="text-center">Employee ID</th>
                                        <th class="text-center">Employee Name</th>
                                        <th class="text-center">Employee Age</th>
                                        <th class="text-center">Designation</th>
                                        @*<th class="text-center">Entry By</th>
                            <th class="text-center">Entry Date</th>
                            <th class="text-center">Update By</th>
                            <th class="text-center">Update Date</th>*@

                                        <th class="text-center" style="padding:18px;">Action</th>
                                    </tr>
                                </thead>
                                <tbody id="dtTableBody">
                                </tbody>
                            </table>

                        </div>

                    </div>




                </div>
            </div>
        </div>
    </div>

</div>


<div class="modal fade" tabindex="-1" id="loginModal"
     data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    ×
                </button>
                @*<h4 class="modal-title"></h4>*@
                <h5 class=""> Employee Entry </h5>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <input class="form-control" type="text"
                               placeholder="Employee Name" id="txtEmpName" />
                    </div>
                    <br />
                    <div class="form-group">
                        <input class="form-control" placeholder="Employee Age"
                               type="number" id="txtEmpAge" />
                    </div>
                    <br />
                    <div class="form-group">
                        <input class="form-control" type="text"
                               placeholder="Employee Designation" id="txtEmpDesignation" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary button button4" onclick="Save()">Submit</button>
                <button type="button" id="btnHideModal" class="btn btn-primary button button4">
                    Hide
                </button>
            </div>
        </div>
    </div>
</div>

<input id="masterId"  style="display:none" />

@section Scripts{



    <script>
        $(function () {

            $(document).ready(function () {
                $("#btnShowModal").click(function () {
                    $("#loginModal").modal('show');
                });

                $("#btnHideModal").click(function () {
                    $("#loginModal").modal('hide');
                });
            });

            GetPrescription();
    });

        function un(o) {
            return o != null ? o : '';
        }





        function ValidationTooltip(id, message) {

            $(id).empty();

            if ($(id).empty()) {
                $(id).append(message);
            }
            $(id).toast('show');
            $(id).css("display", "block");

        }

        function RemoveValidationTooltip(id) {
            $(id).css("display", "none");
        }

        function EmployeeInfoValidation() {

            $('#txtEmpName').removeClass('is-invalid');
            $('#txtEmpAge').removeClass('is-invalid');
            $('#txtEmpDesignation').removeClass('is-invalid');

            RemoveValidationTooltip("#v-txtEmpName");
            RemoveValidationTooltip("#v-txtEmpAge");
            RemoveValidationTooltip("#v-txtEmpDesignation");

            isValid = true;
            if ($('#txtEmpName').val().trim() == "") {

                $('#txtEmpName').addClass("is-invalid");
                ValidationTooltip("#v-txtEmpName", "Please fill out of this field!");
                isValid = false;
            }
            if ($('#txtEmpAge').val().trim() == "") {

                $('#txtEmpAge').addClass("is-invalid");
                ValidationTooltip("#v-txtEmpAge", "Please fill out of this field!");
                isValid = false;
            }

            if ($('#txtEmpDesignation').val().trim() == "") {

                $('#txtEmpDesignation').addClass("is-invalid");
                ValidationTooltip("#v-txtEmpDesignation", "Please fill out of this field!");
                isValid = false;
            }


            return isValid;
        }

        function Save() {

            if (EmployeeInfoValidation()) {
                $.confirm({
                    icon: 'fas fa-question-circle',
                    title: 'Are You Sure ?',
                    content: 'You are about to save the data!',
                    theme: 'Supervan',
                    type: 'green',
                    buttons: {
                        Confirm: {
                            text: 'Confirm',
                            action: function () {
                                FinalSave();
                            }
                        },
                        Cancel: function () {
                        }
                    }
                });

            }


        }

    function FinalSave() {

        var jsonData = {};
        jsonData["EmpId"] = $('#masterId').val();
        jsonData["Name"] = $('#txtEmpName').val();
        jsonData["Age"] = $('#txtEmpAge').val();
        jsonData["Designation"] = $('#txtEmpDesignation').val();

          var urlpath = '@Url.Action("Save_EmployeeInformation", "EmployeeGeneral")';
        $.ajax({
            data: jsonData,
                url: urlpath,
                type: "POST",
                beforeSend: function () {
                    _open_LoadingPopUp_WithMsg("popDiv", "Please wait. Data is Saving...");
                },
                success: function (result) {
                    _close_LoadingPopUp_WithMsg();
                    if (result.isSuccess == true) {
                        $.confirm({
                            icon: 'fas fa-check-circle',
                            title: 'Success !',
                            content: 'Operation successfully done!!',
                            type: 'green',
                            buttons: {
                                OK: {
                                    text: 'OK',
                                    action: function () {
                                var url = '@Url.Action("EmployeeRecords", "EmployeeGeneral")';
                                window.location.href = url;
                                    }
                                }
                            }
                        });

                    } else {
                        _saveErrorDuplicate();
                    }

                },
                error: function (data) {
                    _close_LoadingPopUp_WithMsg();
                    _errorWithMsg("Some error occurred.. Please try again");
                },

            });
        }


        function GetPrescription() {

            var urlpath = '@Url.Action("GetEmployeeInformationList", "EmployeeGeneral")';
            $.ajax({
                url: urlpath,
                dataType: 'json',
                type: "Get",
                async: true,
                beforeSend: function() {
                },
                success: function(data) {

                    $('#tabH').show();
                    var result = JSON.parse(data);
                    var row = "";
                    $('#dtTableBody').html("");
                    for (var i = 0; i < result.length; i++) {
                        row += "<tr>";
                        row += "<td>" + (i + 1) + "</td>";
                        row += "<td>" + un(result[i].ID) + "</td>";
                        row += "<td>" + un(result[i].Name) + "</td>";
                        row += "<td>" + un(result[i].Age) + "</td>";
                        row += "<td>" + un(result[i].Designation) + "</td>";

                        //row += "<td>" + un(result[i].EMPEntryBy) + "</td>";
                        //row += "<td>" + un(result[i].EntryDatee) + "</td>";
                        //row += "<td>" + un(result[i].EMPUpdateBy) + "</td>";
                        //row += "<td>" + un(result[i].UpdateDatee) + "</td>";

                        row += "<td><button class='btn-outline-primary btn-xs mb-1 mb-md-0' onclick='editClick(" + result[i].EmpId + ")'><i class='fas fa-pen' aria-hidden='true'></i></button> </td>";
                        row += "</tr>";
                    }

                    $('#dtTableBody').html(row);
                },
                complete: function () {
                    $('#dtTble').dataTable({
                        "ordering": false
                    });
                }
            });
    }

        function editClick(id) {

            GetData(id);
        }


      function GetData(id) {


            var urlpath = '@Url.Action("GetEmployeeInfoDataForEdit", "EmployeeGeneral")';
            $.ajax({
                url: urlpath,
                dataType: 'json',
                data: { id: id },
                type: "Get",
                async: true,
                success: function (data) {

                    $('#masterId').val(data.EmpId);
                    $('#txtEmpName').val(data.Name);
                    $('#txtEmpAge').val(data.Age);
                    $('#txtEmpDesignation').val(data.Designation);                            
                },
                complete: function () {

                    $("#loginModal").modal('show');
                }
            });
        }


    </script>
}

Lab_Test(30-07-2021)/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Lab_Test(30-07-2021)/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Lab_Test(30-07-2021)/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Lab_Test(30-07-2021)/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>